services:
  app:
    image: debian:latest
    container_name: scout
    environment:
      APP_ID: ${APP_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PUBLIC_KEY: ${PUBLIC_KEY}
    build: ./src
    command: ["node", "app.js"]
    ports:
      - "127.0.0.1:3000:3000"
    expose:
      - "3000"
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      NGROK_DOMAIN: ${NGROK_DOMAIN}
    command:
      - "http"
      - "--domain"
      - "${NGROK_DOMAIN}"
      - "app:3000"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    expose:
      - "4040"
