services:
  app:
    image: debian:latest
    container_name: scout
    environment:
      APP_ID: ${APP_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PUBLIC_KEY: ${PUBLIC_KEY}
      PORT: ${APP_PORT}
    build: ./src
    env_file: .env
    command: ["node", "app.js"]
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    expose:
      - "${APP_PORT}"
    networks:
      - scout-net
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_ALIAS: ${DATABASE_ALIAS}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    networks:
      scout-net:
        aliases:
          - ${DATABASE_ALIAS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  scout-net:
volumes:
  db-data:
